backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Inventory"
    folder: "data/products"
    create: true
    slug: "{{title}}"
    extension: json
    fields:
      - { label: "Product Title (English)", name: "title", widget: "string" }
      - { label: "Urdu Name (اردو نام)", name: "urdu_name", widget: "string", required: false }
      
      - label: "Main Category"
        name: "category"
        widget: "select"
        options: 
          - "ملتانی بیڈ شیٹ سنگل بیڈ"
          - "ملتانی بیڈ شیٹ ڈبل بیڈ"
          - "رشید کاٹن"
          - "رشید لان کاٹن"
          - "LCM سفید لٹھا"
          - "ٹاول"
          - "Special Offer"

      - { label: "Current Price (PKR)", name: "price", widget: "number", value_type: "int" }
      - { label: "Original Price (Before Discount)", name: "old_price", widget: "number", value_type: "int", required: false }
      - { label: "Mark as Sale Item", name: "on_sale", widget: "boolean", default: false, required: false }
      
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Stock Availability", name: "in_stock", widget: "boolean", default: true }
